### PR TITLE
Add basic tests

### PR DESCRIPTION
**Pull request by bobthekingofegypt**
Refactor code to allow testability

Still in progress

### CODE REVIEW

**Comment by jdm** [comment]
@bobthekingofegypt This looks like a good path forward. Thanks for tackling this!

**Comment by bobthekingofegypt** [comment]
I think that is basic test cases for everything in server apart from w3.org/tr [PNG] logic.  I'm not sure exactly what it's aim is.

Some of them are pretty convoluted as it's all one big function, but they should give some coverage.

**Comment by jdm** [comment]
Thanks! This is an improvement on the status quo of no tests, so I'm fine with merging this once it's rebased against master.

**Comment by bobthekingofegypt** [comment]
Was avoiding that as it was a pain.  The conflicts had to be fixed manually, so I created test cases for the regexp changes and I split out storage to allow the ping functionality to continue being tested.

All test cases pass again and it appears to work...

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
